---

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory

- name: copy backend files
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: unpack backend files
  become: yes
  shell: |
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start app 
  become: yes
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
#- name: "Install package dependencies"
#  shell: |
#    cd /root
#    tar -xzvf artifact.tar.gz -C backend
#    rm artifact.tar.gz
#    cd backend
#    npm install
#    npm run build
#    cd dist
#    pm2 stop default
#    pm2 start npm -- start